[package]
name = "gobblytes-fat"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[features]
default = []
std = []

[dependencies]
gibblox-core = { path = "../gibblox-core" }
gobblytes-core = { path = "../gobblytes-core" }
hadris-fat = { version = "1.0.1", default-features = false, features = ["alloc", "async", "read", "lfn"] }
tracing = { version = "0.1.41", default-features = false, features = ["attributes"] }

[dev-dependencies]
async-trait = "0.1.89"
futures = { version = "0.3.31", default-features = false, features = ["executor"] }
