apiVersion: ENC[AES256_GCM,data:wJc=,iv:cQcWqymWG63wCobNwkbopA0aCH4a64pSRzE1z0p5vgY=,tag:yjBRe/5CzrWGboxXyHe+dQ==,type:str]
kind: ENC[AES256_GCM,data:cvT/BpvG,iv:za4L1TrMjc/pCON7L4B+H16Gve/zBq1ZdfNJqXMl5u8=,tag:edP4UN33v13nj1WZDrG4QQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wvdoT3avRpPdZQ==,iv:3orjGZT2QlCf6ks7n90RlxxZn2YZ4jF28gOPwZuZoKM=,tag:j7MUay76Zj1jUFlwgVtY+A==,type:str]
    namespace: ENC[AES256_GCM,data:GdB4ho9L8O+iMvTD,iv:1gZNIXIYKkLG7qIQLPN0uxaDp/beAwSuFBnRfY2jkn0=,tag:6RLIJrLFm2+IhUyE93TKlw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:9UNzzAzLEL8woJ6eJfyZbg38/pgFyIJ85/uXDj1rIo3EoeV4c0TIYQ==,iv:Fa0oVaUNgv6K75YZoXfRD7Dannn5CQAUAW4Cucx2ldE=,tag:aAsr8Xziok9iQn79gbhiDQ==,type:str]
sops:
    age:
        - recipient: age1ajk4j6ph4tk4e0ncux4cgha0gvzjhd56slv7pg7gvdkpdg8ztansyw2d97
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZFJaOUNsajdZcTBTQ2dx
            RWJkN1ZLdXFscVE5cDNHN253VjFwSzRzejBZCkVmdnpkc3N4Y3JVMkpBZHU5d3Bt
            WkNYdWcySS9iaHFUTi9NWkNvemRFaUEKLS0tIHRZdVl6a2x6aFM3YWZQSGIxU0xl
            YVpBMThlcHZ3elhmNDRkeUUyaWl4cTAKy4ruJX/tCPnnrfMCyyPnWOp8NghFLNCc
            2HVAK9pu+/Rw9SeOa3wAhFP3mHDvZf2vXmvCY9I6kiSn6QHYeKi5sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T10:47:29Z"
    mac: ENC[AES256_GCM,data:zTaYaUe4J0ZkRC4f6mTU1EtWUs/U0Jf9n3PK3ghiRyD69mItEEj1db7kymNXuV3w0S3iP9DZJp4QsD5XNJIK31X+hpGt9uAg13+ELPHHTzATDs7pUdLj3Z+7qSe5lZRmNMseq6zhOVPVrOLlMhiZsJkHt00m6WMgCK1X9lvsNlc=,iv:lhX//wLWFSQRFJmSUXW8+LmstTzLvne9eI2oGkOiBfM=,tag:log8N8tXEcKqUsWjeHUjkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
