[package]
name = "fastboop-web"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
anyhow = "1.0.91"
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
fastboop-core = { path = "../../crates/fastboop-core" }
fastboop-rootfs-erofs = { path = "../../crates/fastboop-rootfs-erofs" }
fastboop-stage0-generator = { path = "../../crates/fastboop-stage0-generator" }
fastboop-fastboot-webusb = { path = "../../crates/fastboop-fastboot-webusb" }
gibblox-core = { path = "../../gibblox/crates/gibblox-core" }
gibblox-cache = { path = "../../gibblox/crates/gibblox-cache", features = ["std"] }
gibblox-cache-store-opfs = { path = "../../gibblox/crates/gibblox-cache-store-opfs" }
gibblox-http = { path = "../../gibblox/crates/gibblox-http", default-features = false, features = ["wasm-client"] }
gibblox-zip = { path = "../../gibblox/crates/gibblox-zip" }
gibblox-web-worker = { path = "../../gibblox/crates/gibblox-web-worker" }
url = "2.5.4"
smoo-host-core = { path = "../../smoo/crates/smoo-host-core" }
smoo-host-session = { path = "../../smoo/crates/smoo-host-session" }
smoo-host-blocksource-gibblox = { path = "../../crates/smoo-host-blocksource-gibblox" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["fmt", "registry", "std"] }
tracing-wasm = "0.2.1"
futures-channel = "0.3"
futures-util = { version = "0.3.31", default-features = false, features = ["alloc", "async-await"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
js-sys = "0.3.82"
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
web-sys = { version = "0.3.82", features = ["DedicatedWorkerGlobalScope", "Document", "Event", "HtmlCollection", "HtmlScriptElement", "MessageChannel", "MessageEvent", "MessagePort", "Navigator", "ReadableStream", "ReadableStreamDefaultReader", "Serial", "SerialOptions", "SerialPort", "SerialPortFilter", "SerialPortInfo", "SerialPortRequestOptions", "Usb", "UsbDevice", "UsbDeviceFilter", "UsbDeviceRequestOptions", "Window", "Worker", "WorkerGlobalScope", "WorkerNavigator", "WorkerOptions", "WorkerType"] }

[features]
default = ["web"]
web = ["dioxus/web"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
smoo-host-web-worker = { path = "../../smoo/crates/smoo-host-web-worker" }
smoo-host-webusb = { path = "../../smoo/crates/smoo-host-webusb" }
