[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
fastboop-core = { path = "../../crates/fastboop-core" }
fastboop-fastboot-webusb = { path = "../../crates/fastboop-fastboot-webusb" }
js-sys = "0.3.76"
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"
web-sys = { version = "0.3.76", features = ["Navigator", "Usb", "UsbDevice", "UsbDeviceFilter", "UsbDeviceRequestOptions", "Window"] }

[features]
default = ["web"]
web = ["dioxus/web"]
