[package]
name = "fastboop-web"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
fastboop-core = { path = "../../crates/fastboop-core" }
fastboop-stage0-generator = { path = "../../crates/fastboop-stage0-generator" }
fastboop-fastboot-webusb = { path = "../../crates/fastboop-fastboot-webusb" }
gobblytes-erofs = { version = ">=0.0.1-rc.8" }
gobblytes-core = { version = ">=0.0.1-rc.8" }
gibblox-core = { version = ">=0.0.1-rc.8" }
gibblox-cache = { version = ">=0.0.1-rc.8", features = ["std"] }
gibblox-cache-store-opfs = { version = ">=0.0.1-rc.8" }
gibblox-casync = { version = ">=0.0.1-rc.8" }
gibblox-casync-web = { version = ">=0.0.1-rc.8" }
gibblox-android-sparse = { version = ">=0.0.1-rc.8" }
gibblox-http = { version = ">=0.0.1-rc.8", default-features = false, features = ["wasm-client"] }
gibblox-mbr = { version = ">=0.0.1-rc.8" }
gibblox-xz = { version = ">=0.0.1-rc.8" }
gibblox-zip = { version = ">=0.0.1-rc.8" }
gibblox-web-file = { version = ">=0.0.1-rc.8" }
gibblox-blockreader-messageport = { version = ">=0.0.1-rc.8" }
gibblox-web-worker = { version = ">=0.0.1-rc.8" }
url = { workspace = true }
smoo-host-core = { path = "../../smoo/crates/smoo-host-core" }
smoo-host-session = { path = "../../smoo/crates/smoo-host-session" }
smoo-host-blocksource-gibblox = { path = "../../smoo/crates/smoo-host-blocksource-gibblox" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["fmt", "registry", "std"] }
tracing-wasm = "0.2.1"
futures-channel = { workspace = true }
futures-util = { workspace = true, features = ["alloc", "async-await"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
js-sys = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["DedicatedWorkerGlobalScope", "Document", "Event", "HtmlCollection", "HtmlScriptElement", "MessageChannel", "MessageEvent", "MessagePort", "Navigator", "ReadableStream", "ReadableStreamDefaultReader", "Serial", "SerialOptions", "SerialPort", "SerialPortFilter", "SerialPortInfo", "SerialPortRequestOptions", "Usb", "UsbDevice", "UsbDeviceFilter", "UsbDeviceRequestOptions", "Window", "Worker", "WorkerGlobalScope", "WorkerNavigator", "WorkerOptions", "WorkerType"] }

[features]
default = ["web"]
web = ["dioxus/web"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
smoo-host-web-worker = { path = "../../smoo/crates/smoo-host-web-worker" }
smoo-host-webusb = { path = "../../smoo/crates/smoo-host-webusb" }
