[package]
name = "fastboop-web"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
fastboop-core = { path = "../../crates/fastboop-core" }
fastboop-fastboot-webusb = { path = "../../crates/fastboop-fastboot-webusb" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["fmt", "registry", "std"] }
tracing-wasm = "0.2.1"

[features]
default = ["web"]
web = ["dioxus/web"]
