[package]
name = "fastboop-desktop"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
fastboop-core = { path = "../../crates/fastboop-core" }
fastboop-stage0-generator = { path = "../../crates/fastboop-stage0-generator" }
fastboop-fastboot-rusb = { path = "../../crates/fastboop-fastboot-rusb" }
gobblytes-erofs = { version = "=0.0.1-rc.6" }
gibblox-core = { version = "=0.0.1-rc.6", features = ["std"] }
gibblox-cache = { version = "=0.0.1-rc.6", features = ["std"] }
gibblox-cache-store-std = { version = "=0.0.1-rc.6" }
gibblox-http = { version = "=0.0.1-rc.6", default-features = false, features = ["native-client"] }
gibblox-zip = { version = "=0.0.1-rc.6", features = ["std"] }
smoo-host-core = { path = "../../smoo/crates/smoo-host-core" }
smoo-host-session = { path = "../../smoo/crates/smoo-host-session" }
smoo-host-transport-rusb = { path = "../../smoo/crates/smoo-host-transport-rusb" }
smoo-host-blocksource-gibblox = { path = "../../crates/smoo-host-blocksource-gibblox" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-util = { workspace = true }
url = { workspace = true }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
native = ["dioxus/native"]
