[package]
name = "fastboop-desktop"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
fastboop-core = { path = "../../crates/fastboop-core" }
fastboop-fastboot-rusb = { path = "../../crates/fastboop-fastboot-rusb" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[features]
default = ["native"]
desktop = ["dioxus/desktop"]
native = ["dioxus/native"]
