[package]
name = "fastboop-desktop"
version.workspace = true
edition = "2021"
license.workspace = true

[dependencies]
anyhow = "1.0.91"
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
fastboop-core = { path = "../../crates/fastboop-core" }
fastboop-erofs-rootfs = { path = "../../crates/fastboop-erofs-rootfs" }
fastboop-stage0-generator = { path = "../../crates/fastboop-stage0-generator" }
fastboop-fastboot-rusb = { path = "../../crates/fastboop-fastboot-rusb" }
gibblox-core = { path = "../../gibblox/crates/gibblox-core", features = ["std"] }
smoo-host-core = { path = "../../smoo/crates/smoo-host-core", features = ["std"] }
smoo-host-transport-rusb = { path = "../../smoo/crates/smoo-host-transport-rusb" }
smoo-host-blocksource-gibblox = { path = "../../crates/smoo-host-blocksource-gibblox" }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-util = "0.7.17"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
native = ["dioxus/native"]
