apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontdoor-tls
spec:
  secretName: frontdoor-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - fastboop.win
    - www.fastboop.win
    - flux.fastboop.win
    - matrix.fastboop.win
