apiVersion: v1
kind: Service
metadata:
  name: frontdoor
  annotations:
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/name: fastboop-frontdoor
    load-balancer.hetzner.cloud/use-private-ip: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    external-dns.alpha.kubernetes.io/hostname: fastboop.win,www.fastboop.win,flux.fastboop.win,matrix.fastboop.win
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frontdoor
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
