apiVersion: v1
kind: Service
metadata:
  name: fastboop-web
spec:
  selector:
    app.kubernetes.io/name: fastboop-web
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
