[package]
name = "fastboop-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.91"
async-trait = "0.1.89"
clap = { version = "4.5.21", features = ["derive"] }
fastboop-core = { path = "../crates/fastboop-core" }
fastboop-erofs-rootfs = { path = "../crates/fastboop-erofs-rootfs" }
fastboop-stage0-generator = { path = "../crates/fastboop-stage0-generator" }
fastboop-fastboot-rusb = { path = "../crates/fastboop-fastboot-rusb" }
pollster = "0.3.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
gibblox-core = { path = "../gibblox/crates/gibblox-core", features = ["std"] }
smoo-host-core = { path = "../smoo/crates/smoo-host-core", features = ["std"] }
smoo-host-transport-rusb = { path = "../smoo/crates/smoo-host-transport-rusb" }
smoo-host-blocksource-gibblox = { path = "../crates/smoo-host-blocksource-gibblox" }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-util = "0.7.17"
url = "2.5.4"
