[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.21", features = ["derive"] }
fastboop-core = { path = "../crates/fastboop-core" }
fastboop-stage0 = { path = "../crates/fastboop-stage0" }
fastboop-fastboot-rusb = { path = "../crates/fastboop-fastboot-rusb" }
pollster = "0.3.0"
rusb = "0.9.4"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
