[package]
name = "fastboop-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
fastboop-core = { path = "../crates/fastboop-core" }
fastboop-stage0-generator = { path = "../crates/fastboop-stage0-generator" }
fastboop-fastboot-rusb = { path = "../crates/fastboop-fastboot-rusb" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = { workspace = true }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
gibblox-core = { version = "=0.0.1-rc.6", features = ["std"] }
gibblox-ext4 = { version = "=0.0.1-rc.6" }
gibblox-mbr = { version = "=0.0.1-rc.6", features = ["std"] }
gibblox-casync = { version = "=0.0.1-rc.6", features = ["std"] }
gibblox-casync-std = { version = "=0.0.1-rc.6" }
gibblox-cache = { version = "=0.0.1-rc.6", features = ["std"] }
gibblox-cache-store-std = { version = "=0.0.1-rc.6" }
gibblox-file = { version = "=0.0.1-rc.6" }
gibblox-http = { version = "=0.0.1-rc.6", default-features = false, features = ["native-client"] }
gibblox-android-sparse = { version = "=0.0.1-rc.6", features = ["std"] }
gibblox-xz = { version = "=0.0.1-rc.6", features = ["std"] }
gibblox-zip = { version = "=0.0.1-rc.6", features = ["std"] }
gobblytes-core = { version = "=0.0.1-rc.6" }
gobblytes-erofs = { version = "=0.0.1-rc.6" }
gobblytes-fat = { version = "=0.0.1-rc.6" }
smoo-host-core = { path = "../smoo/crates/smoo-host-core" }
smoo-host-session = { path = "../smoo/crates/smoo-host-session" }
smoo-host-transport-rusb = { path = "../smoo/crates/smoo-host-transport-rusb" }
smoo-host-blocksource-gibblox = { path = "../crates/smoo-host-blocksource-gibblox" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "time"] }
tokio-util = { workspace = true }
url = { workspace = true }
ratatui = "0.29.0"
crossterm = "0.28.1"
