apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix
  namespace: conduit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - matrix.fastboop.win
      secretName: matrix-fastboop-win-tls
  rules:
    - host: matrix.fastboop.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: conduit-generic
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matrix-well-known
  namespace: conduit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fastboop.win
      secretName: fastboop-win-tls
  rules:
    - host: fastboop.win
      http:
        paths:
          - path: /.well-known/matrix
            pathType: Prefix
            backend:
              service:
                name: matrix-well-known
                port:
                  number: 80
