[package]
name = "fastboop-mobile"
version.workspace = true
edition = "2021"
license.workspace = true
publish = false

[dependencies]
dioxus = { workspace = true, features = ["router"] }
ui = { workspace = true }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }

[features]
default = ["mobile"]
mobile = ["dioxus/mobile"]
