[package]
name = "smoo-host-blocksource-gibblox"
version = { workspace = true }
edition = "2024"
rust-version = { workspace = true }
license = "GPL-3.0-only"

[dependencies]
async-trait = "0.1.89"
gibblox-core = { path = "../../gibblox/crates/gibblox-core", features = ["std"] }
smoo-host-core = { path = "../../smoo/crates/smoo-host-core", features = ["std"] }
