[package]
name = "fastboop-stage0"
version = "0.1.0"
edition = "2024"

[dependencies]
fastboop-core = { path = "../fastboop-core" }
fdt = { version = "0.1.5", default-features = false }

[features]
default = []
std = []
