apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - repositories.yaml
  - cert-manager
  - fastboop-web
  - frontdoor
  - external-dns
  - conduit
  - gha-proxy
  - flux-system
