apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gha-proxy
spec:
  hostnames:
    - fastboop.win
  parentRefs:
    - name: public
      namespace: ingress-nginx
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /gha
      backendRefs:
        - name: gha-proxy
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fastboop-apex-redirects
spec:
  hostnames:
    - fastboop.win
  parentRefs:
    - name: public
      namespace: ingress-nginx
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /device-permissions
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: docs.fastboop.win
            path:
              type: ReplaceFullPath
              replaceFullPath: /user/device-permissions/
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            hostname: www.fastboop.win
