[package]
name = "gibblox-ext4"
version = "0.1.0"
edition = "2021"

[dependencies]
ext4-view = "0.9.3"
gibblox-core = { path = "../gibblox-core" }
async-trait = "0.1"
pollster = "0.3"
spin = "0.10"

[lib]
