[package]
name = "erofs-rs"
version = "0.1.1"
edition = "2024"
authors = ["Dreamacro"]
description = "A pure Rust library for reading EROFS (Enhanced Read-Only File System) images"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Dreamacro/erofs-rs"
keywords = ["erofs", "filesystem", "readonly", "linux"]
categories = ["filesystem"]
readme = "../README.md"
rust-version = "1.88"

[lints]
workspace = true

[dependencies]
bitflags = { workspace = true }
async-trait = "0.1.89"
lz4_flex = { version = "0.12.0", default-features = false, features = ["safe-decode"] }
miniz_oxide = { version = "0.9.0", default-features = false, features = ["with-alloc"] }
spin = { version = "0.10.0", default-features = false, features = ["mutex", "spin_mutex"] }
