[package]
name = "fastboop-core"
version = "0.1.0"
edition = "2024"

[dependencies]
fastboop-schema = { workspace = true }
postcard = { version = "1.1.3", default-features = false, features = ["alloc"] }
serde = { version = "1.0.217", default-features = false, features = ["derive", "alloc"] }
schemars = { version = "0.8.21", optional = true, features = ["preserve_order"] }
tracing = { version = "0.1.44", default-features = false }

[build-dependencies]
fastboop-schema = { workspace = true, features = ["std"] }
postcard = { version = "1.1.3", features = ["alloc"] }
serde_yaml = "0.9.34"

[features]
default = []
std = ["serde/std", "fastboop-schema/std"]
schema = ["std", "schemars", "fastboop-schema/schema"]
